name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Yarn install
        run: yarn install --immutable

  format:
    name: Format
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Run format
        run: yarn format --check

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Run lint
        run: yarn lint

  build:
    name: Build
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Run build
        run: yarn build
